# Docker Compose simplificado para EasyPanel
# automaticpdfhub.cloud - Arquitectura optimizada para producción
version: '3.8'

services:
  # =====================================
  # BASE DE DATOS
  # =====================================
  postgres:
    image: postgres:15-alpine
    container_name: automaticpdf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: automaticpdf_db
      POSTGRES_USER: automaticpdf_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5487:5432"
    volumes:
      - /opt/easypanel/projects/hubspot-pdf/postgres:/var/lib/postgresql/data
    networks:
      - automaticpdf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automaticpdf_user -d automaticpdf_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================
  # CACHE REDIS
  # =====================================
  redis:
    image: redis:7-alpine
    container_name: automaticpdf-redis
    restart: unless-stopped
    ports:
      - "6418:6379"
    volumes:
      - /opt/easypanel/projects/hubspot-pdf/redis:/data
    networks:
      - automaticpdf-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================
  # SERVICIO PDF GOTENBERG
  # =====================================
  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: automaticpdf-gotenberg
    restart: unless-stopped
    ports:
      - "3021:3000"
    networks:
      - automaticpdf-network
    command:
      - "gotenberg"
      - "--chromium-disable-web-security"
      - "--log-level=warn"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================
  # BACKEND API
  # =====================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: automaticpdf-backend
    restart: unless-stopped
    ports:
      - "3022:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      gotenberg:
        condition: service_healthy
    environment:
      NODE_ENV: production
      APP_PORT: 3002
      FRONTEND_URL: https://automaticpdfhub.cloud
      DATABASE_URL: postgresql://automaticpdf_user:${POSTGRES_PASSWORD}@postgres:5432/automaticpdf_db?schema=public
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      GOTENBERG_URL: http://gotenberg:3000
      HUBSPOT_CLIENT_ID: ${HUBSPOT_CLIENT_ID}
      HUBSPOT_CLIENT_SECRET: ${HUBSPOT_CLIENT_SECRET}
      HUBSPOT_REDIRECT_URI: https://automaticpdfhub.cloud/api/auth/hubspot/callback
      JWT_SECRET: ${JWT_SECRET}
      STORAGE_PATH: /app/storage
      FILE_BASE_URL: https://automaticpdfhub.cloud/files
      DOCUMENT_CONCURRENCY: 3
      HUBSPOT_CONCURRENCY: 2
      LOG_LEVEL: warn
      MAX_FILE_SIZE_MB: 25
    volumes:
      - /opt/easypanel/projects/hubspot-pdf/storage:/app/storage
      - /opt/easypanel/projects/hubspot-pdf/logs:/app/logs
    networks:
      - automaticpdf-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================
  # FRONTEND REACT
  # =====================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        REACT_APP_API_URL: https://automaticpdfhub.cloud/api
        REACT_APP_FILES_URL: https://automaticpdfhub.cloud/files
        REACT_APP_ENV: production
    container_name: automaticpdf-frontend
    restart: unless-stopped
    ports:
      - "3020:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - automaticpdf-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================
  # NGINX REVERSE PROXY
  # =====================================
  nginx:
    image: nginx:alpine
    container_name: automaticpdf-nginx
    restart: unless-stopped
    ports:
      - "8095:80"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    volumes:
      - ./deployment/nginx-production.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - automaticpdf-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# =====================================
# RED DOCKER
# =====================================
networks:
  automaticpdf-network:
    driver: bridge
    external: false

# =====================================
# LABELS PARA EASYPANEL
# =====================================
labels:
  - "easypanel.project=hubspot-pdf-generator"
  - "easypanel.domain=automaticpdfhub.cloud"
  - "easypanel.port=8095"
